### ISSUE TITLE
Automatic doc build failing

### ISSUE THREAD

**Issue by amilsted** [qojulia/QuantumOptics.jl-documentation#18]
Hi @david-pl, it looks like the build/deploy workflow is failing because of a matplotlib error at the moment. Have you seen this before?

**Comment by Krastanov** [comment]
suspicious that a breaking release of numpy was released last week (for the first time in a decade)

**Comment by david-pl** [comment]
Hm odd, no haven't seen that before. Did anybody try building this locally?

**Comment by david-pl** [comment]
Looks like the issue is actually a new matplotlib version and a call by PyPlot to an outdated API. The fix is already merged in PyPlot (https://github.com/JuliaPy/PyPlot.jl/pull/583), but there's no patch release yet.

I "fixed" it for now in #19 by pinning matplotlib to 3.8. In the long term, we should probably change to a different plotting library for the examples, but for now it's fine I suppose.

**Comment by david-pl** [comment]
FYI, the successful run in the PR already deployed the latest version of the docs. I'll leave the PR dangling for a few days and merge then if there are no comments.

**Comment by amilsted** [comment]
Looks good to me!

**Comment by amilsted** [comment]
Thanks for fixing this.
